#!/bin/bash

# > extract_draw.sh <
# Converts the code generated by Mike Swanson's Ai->Canvas Export Plug-In 
# for Illustrator into an expression that stores the draw() function
# in a custom JavaScript array member.

# Storing these vector drawing instructions in an array gives me options
# for calling them sequentially in an animation.

# Learn more about the Ai->Canvas Export Plug-In at 
# http://visitmix.com/labs/ai2canvas.

# Written by parisminton for Concrete Daydreams.
# <parisminton@da.ydrea.ms>

#vrs="v 0.1"
#last_change="10/30/11"

OLD_IFS=$IFS
IFS=$(echo -en "\n\b")

character=$1
args=$(ls -1 *.html)

echo "$character = new Character(\"$character\", false);
$character.show();
$character.sequence.main.cels = [" > cels.js


for filename in $args; do

  name=$(echo $filename) 
  index=$(echo $name | sed -n 's/[a-zA-Z_.\-]*\([0-9][0-9]*\)[a-zA-Z_.\-]*\.html$/\1/p')

  sed '
      /function vaulter/, /}$/ !d
        s/    function/function/
        s/vaulter(ctx)/(ctx)/
        s/function/  pv.cels['"$index"']= {\
      breakpoint : false\,\
      render\ :\ function/
        s/}$/}\
  };/
      ' < $filename >> cels.js

done

IFS=$OLD_IFS
