#!/bin/bash

# > extract_draw.sed <
# Converts the code generated by the AI->Canvas Export Plug-In for Illustrator into an expression that stores the draw() function in a JavaScript array member.
# Written by parisminton for Concrete Daydreams.
# <parisminton@da.ydrea.ms>

#vrs="0.1"
#last_change="10/28/11"

sed '
    21, /}$/ !d
      s/    function/function/
      s/draw(ctx)/(ctx)/
      s/function/  pv.cels[1]= {\
    breakpoint : false\,\
    render\ :\ function/
    ' < $1 > chesapeake.txt
